@startuml
'skinparam lifelineStrategy 
boundary "__:FormMain__" as formMain
boundary "__:MutualGroupsList__" as mutualGroups
boundary "__userPanel1: UserPanel__" as u1
boundary "__userPanel2: UserPanel__" as u2
control "AppLogic" as logic
collections "User1 Groups:Group" as g1
collections "User2 Groups:Group" as g2
collections "logic common groups : Group" as lcg



group Find Common Groups [Two users are logged]
    formMain -\\ u1 : get groups 
    u1 -// formMain : (groups)
    formMain -\\ u2 : get groups
    u2 -// formMain : (groups)
    formMain -\\ logic : IntersectGroups(groupsList)
    loop for all groups from user 1
        logic -// g1 : getCurrentGroupId()
        g1 -\\ logic: id 
        
            loop for all groups from user 2
                logic -// g2 : getCurrentGroupId()
                g2 -\\ logic: id 
                opt ids are equal
                    logic -// lcg : addGroup
                    lcg -\\ logic : (void)
                end
                
            end 
        
     end
    
    logic -// formMain: (Intersected groups / interests)
    mutualGroups //- formMain : present Intersected groups / Intersts
    formMain \\- mutualGroups : (void)
end   
@enduml