@startuml
left to right direction
actor First_User as user1
actor Second_User as user2

package Halfway {
  usecase "Find Common Interests" as interUC
  usecase "Find the  venue with another" as venueUC
  usecase "Find the likelihood for bonding" as matchUC
  usecase "Get a dashboard of the user data" as dashUC
  usecase "Compare two users" as compareMTD 
  usecase "Login" as loginMTD 


}
note right of interUC : Potentially common groups\n or pages
note right of matchUC : Represented as the average age \n but can be easily expanded with \nmore parameters 
 
user1 ..> interUC
user1 ..> venueUC
user1 ..> matchUC
user1 ..> dashUC

user2 ..> interUC
user2 ..> venueUC
user2 ..> matchUC
user1 ..> dashUC

(interUC) ..> (compareMTD) : <<include>>
(venueUC) ..> (compareMTD) : <<include>>
(matchUC) ..> (compareMTD) : <<include>>

(interUC) ..> (loginMTD) : <<extends>>
(venueUC) ..> (loginMTD) : <<extends>>
(matchUC) ..> (loginMTD) : <<extends>>
(dashUC) ..> (loginMTD) : <<extends>>



@enduml