@startuml
class FormattedAlbum
{
    +   string ToString()
}
class FormattedPage
{
    +   string ToString()
}
class Album
{
    + FacebookObjectCollection<Photo> Photos
    + long Count
    + string PictureAlbumURL
    +  string ToString()
}

class Page
{
    + string Description()
    + Image ImageLarge()
    +   string ToString()
}
class ListBox
{
}
note "Blue = original use\nOrange = adapted use" as nt
FormattedAlbum o-- Album
FormattedPage o-- Page
ListBox -[#orange]-> FormattedAlbum
ListBox -[#orange]-> FormattedPage
ListBox -[#blue]-> Page
ListBox -[#blue]> Album
@enduml